---
- name: Deploy and Map VLAN to VXLAN
  hosts: network
  gather_facts: False
  vars_files:
    - vars/vxlan_vars.yaml

  tasks:
    - name: Task 01 - Verify and deploy VLANs mapped to VNIs
      nxos_vlan:
        state: present
        vlan_id: "{{ item.vlan_id }}"
        admin_state: up
        name: "{{ item.vlan_name }}"
        mapped_vni: "{{ item.vni }}"
      with_items: "{{ vlan }}"

    - name: Task 02 - Verify NVE is configured with VNIs
      nxos_vxlan_vtep_vni:
        state: present
        interface: nve1
        vni: "{{ item.vni }}"
        ingress_replication: bgp
        suppress_arp: yes
      with_items: "{{ vlan }}"

    - name: Task 03 - Verify and deploy VNI configuration to EVPN
      nxos_evpn_vni:
        state: present
        vni: "{{ item.vni }}"
        route_distinguisher: auto
        route_target_import: auto
        route_target_export: auto
      with_items: "{{ vlan }}"

    - name: Task 04 - Create SVI with anycast gateway
      nxos_interface:
        state: present
        name: "Vlan{{ item.vlan_id }}"
        description: "{{ item.description }}"
        fabric_forwarding_anycast_gateway: yes
      with_items: "{{ vlan }}"

    - name: Task 05 - Assign SVI to vrf
      nxos_vrf_interface:
        state: present
        vrf: "{{ item.vrf }}"
        interface: "Vlan{{ item.vlan_id }}"
      with_items: "{{ vlan }}"

    - name: Task 06 - Assign IP to SVI
      nxos_l3_interface:
        state: present
        name: "Vlan{{ item.vlan_id }}"
        ipv4: "{{ item.ipv4 }}"
      with_items: "{{ vlan }}"
      tags: debug

    - name: Task 07 - Map VLAN to Physical Interface
      when: (inventory_hostname == "192.168.122.139") or
            (inventory_hostname == "192.168.122.138")
      nxos_switchport:
        state: present
        interface: "{{ item.iface }}"
        mode: "{{ item.port_mode }}"
        access_vlan: "{{ item.vlan_id }}"
      with_items: "{{ switch_iface }}"
